name: Update Git Submodules

on:
  schedule:
    - cron: '30 3 * * 0'

jobs:
  SubmoduleSync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
        with:
          submodules: true

      - name: Attempt to update Git Submodules
        uses: git pull --recurse-submodules && git submodule update --remote --recursive

      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit any changes and create a pull request
        run: |
          git add --all .;
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            git commit -snam "chore: updated GitHub Submodules at $(date '+%F %H:%M.%S')" || true;
            git push origin main
          fi
